{
 "title": "OpenShift Cluster Summary - Custom",
 "description": "Summary metrics about containers running on Kubernetes nodes and mainline kubernetes statistics",
 "tags": [
  "kubernetes",
  "kubernetes-app",
  "openshift"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": "prometheus" },
   { "name": "ds", "query": "datasource" },
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "node",
    "query": "label_values(node_boot_time{job=\"node-exporter\"}, instance)"
   },
   {
    "name": "namespace",
    "query": "label_values(kube_pod_info, namespace)"
   }
  ]
 },
 "panels": [
  { "title": "Cluster Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Pod Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_info) / sum(kube_node_status_allocatable_pods) * 100"
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores) / sum(kube_node_status_allocatable_cpu_cores) * 100"
    }
   ]
  },
  {
   "title": "Cluster Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes) / sum(kube_node_status_allocatable_memory_bytes) * 100"
    }
   ]
  },
  {
   "title": "Cluster Disk Usage",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum (node_filesystem_files{mountpoint=\"/\"}) - sum(node_filesystem_files_free{mountpoint=\"/\"})) / sum (node_filesystem_files{mountpoint=\"/\"})"
    }
   ]
  },
  {
   "title": "Cluster Pod Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short", "label": "pods" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_pods)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_pods)",
     "legendFormat": "capacity"
    },
    { "expr": "sum(kube_pod_info)", "legendFormat": "requested" }
   ]
  },
  {
   "title": "Cluster CPU Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity_cpu_cores)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_allocatable_cpu_cores)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_cpu_cores)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Mem Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_allocatable_memory_bytes)",
     "legendFormat": "allocatable"
    },
    {
     "expr": "sum(kube_node_status_capacity_memory_bytes)",
     "legendFormat": "capacity"
    },
    {
     "expr": "sum(kube_pod_container_resource_requests_memory_bytes)",
     "legendFormat": "requested"
    }
   ]
  },
  {
   "title": "Cluster Disk Capacity",
   "type": "graph",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_files{mountpoint=\"/\"}) - sum(node_filesystem_files_free{mountpoint=\"/\"})",
     "legendFormat": "usage"
    },
    {
     "expr": "sum(node_filesystem_size{nodename=~\"$node\"})",
     "legendFormat": "limit"
    }
   ]
  },
  {
   "title": "Node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number Of Nodes",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 11 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      { "expr": "sum(kube_node_info)" }
     ]
    },
    {
     "title": "Filesystem usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 21, "x": 3, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\",node=~\"^$Node$\"}) * 100"
      },
      {
       "expr": "sum (container_fs_usage_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node) / sum (container_fs_limit_bytes{device=~\"^/dev/.*$\",id=\"/\"}) by (node) * 100"
      }
     ]
    },
    {
     "title": "Nodes Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 14 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_spec_unschedulable)"
      }
     ]
    },
    {
     "title": "Nodes Out of Disk",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 0, "y": 17 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_node_status_condition{condition=\"OutOfDisk\", status=\"true\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Projects",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Request Allocation per Project",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum ((kube_pod_container_resource_requests_cpu_cores{container!=\"docker-build\"})*1000) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    },
    {
     "title": "Memory Request Allocation per Project",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum ((kube_pod_container_resource_requests_memory_bytes)) by (namespace)",
       "legendFormat": "{{namespace}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Deployments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Deployment Replicas - Up To Date",
     "type": "table-old",
     "gridPos": { "h": 5, "w": 10, "x": 0, "y": 22 },
     "targets": [
      {
       "expr": "kube_deployment_status_replicas{namespace=~\"$namespace\"}",
       "legendFormat": "{{ deployment }}"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Updated",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 10, "y": 22 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_updated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas - Unavailable",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 14, "y": 22 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_unavailable{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Deployment Replicas",
     "type": "singlestat",
     "gridPos": { "h": 5, "w": 4, "x": 18, "y": 22 },
     "format": "none",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Pods",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Running\"})"
      }
     ]
    },
    {
     "title": "Pods Pending",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 5 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Pending\"})"
      }
     ]
    },
    {
     "title": "Pods Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Failed\"})"
      }
     ]
    },
    {
     "title": "Pods Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Succeeded\"})"
      }
     ]
    },
    {
     "title": "Pods Unknown",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 8 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{namespace=~\"$namespace\", phase=\"Unknown\"})"
      }
     ]
    },
    {
     "title": "Pods per Node",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      { "expr": "sum (kube_pod_info) by (node)", "legendFormat": "{{ node }}" }
     ]
    },
    {
     "title": "Pod Phases",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase) by (phase)",
       "legendFormat": "{{phase}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Containers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Containers Running",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_running{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Waiting",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_waiting{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Terminated",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_status_terminated{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Containers Restarts (Last 30 Minutes)",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 6 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(delta(kube_pod_container_status_restarts_total{namespace!=\"kube-system\"}[30m]))"
      }
     ]
    },
    {
     "title": "CPU Cores Requested by Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 0, "y": 9 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_cpu_cores{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Memory Requested By Containers",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 12, "x": 12, "y": 9 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_requests_memory_bytes{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 0, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_succeeded{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Succeeded",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 8, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_active{namespace=~\"$namespace\"})"
      }
     ]
    },
    {
     "title": "Jobs Failed",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 8, "x": 16, "y": 7 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(kube_job_status_failed{namespace=~\"$namespace\"})"
      }
     ]
    }
   ]
  }
 ]
}